trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '17'
    addToPath: true

- script: |
    java -version
    mvn clean install
  displayName: 'Maven Clean Install'
