trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'
steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17' # Specify the JDK version you want, in this case, Java 8.
    jdkArchitectureOption: 'x64' # You can choose 'x64' or 'x86' based on your architecture.
    jdkSourceOption: 'PreInstalled' # Use 'PreInstalled' if the JDK is pre-installed on the build agent.
    
- script: |
    java -version
    mvn clean install -DskipTests
  displayName: 'Maven Clean Install'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'EpayNexusAPIServiceConnection'
    organization: 'epaynexusapi'
    scannerMode: 'Other'
    extraProperties: |
      sonar.projectKey=dhiasdr_TestAzurePipeline
      sonar.projectName=TestAzurePipeline
      
- script: 'mvn sonar:sonar'
  displayName: 'Run SonarCloud Analysis'
- task: SonarCloudPublish@1