trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - script: echo "Build started"

  - task: UseJavaVersion@1
    inputs:
      versionSpec: '17'
      addToPath: true

  - script: |
      mvn clean install
    displayName: 'Maven Clean Install'

  - script: echo "Build completed"

- job: NotifyByEmail
  dependsOn: Build
  condition: succeededOrFailed()
  steps:
  - task: Email@1
    inputs:
      To: 'dhiasdiri17@gmail.com'
      Subject: 'Azure Pipelines Build Status'
      Body: |
        Dear ${commitAuthor},
        
        The Azure Pipelines build for commit ${commitSha} on branch ${buildSourceBranch} has completed with status: ${buildStatus}.
        
        Thank you,
        Your CI/CD Bot
      SendOnBehalfOf: 'dhiasdiri17@hotmail.com'
    env:
      commitAuthor: $(Build.SourceVersionAuthor)
      commitSha: $(Build.SourceVersion)
      buildSourceBranch: $(Build.SourceBranch)
      buildStatus: $(Build.Result)
