trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '17'
    addToPath: true

- script: 'mvn clean install'
  displayName: 'Maven Clean Install'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'API-EpayNexus' # Replace with the name of your SonarCloud service connection
    organization: 'EpayNexus'
    scannerMode: 'MSBuild'
    projectKey: 'dhiasdiri17_EpayNexus-Aventix-API'
    projectName: 'EpayNexus-Aventix-API'

- script: 'mvn sonar:sonar'
  displayName: 'Run SonarCloud Analysis'

- task: SonarCloudPublish@1

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'deploy'
    options: '-X'
  condition: succeededOrFailed()
