steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'API-EpayNexus'
    organization: 'epaynexus'
    scannerMode: 'Other'
    extraProperties: |
      sonar.projectKey=dhiasdiri17_EpayNexus-Aventix-API
      sonar.projectName=EpayNexus-Aventix-API